<?php

namespace AppBundle\Repository;

/**
 * EmojiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmojiRepository extends \Doctrine\ORM\EntityRepository
{

}
