<?php

namespace AppBundle\Repository;


/**
 * TranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByLanguage($language)
    {
        if(null === $language || $language == 'english'){

            return $this->getEntityManager()->getRepository('AppBundle:Emoji')->findAll();
        }
        $emojisArray = [];
        $translations = $this->findBy(['language'=>$language]);
        foreach ($translations as $translation){
            $translateEmoji = $translation->getTranslation();
            $emoji = $translation->getEmoji();
            $emoji->setTranslate($translateEmoji);
            $emojisArray[] = $emoji;
        }
        return $emojisArray;
    }


}
